### PR TITLE
Update rld sources to the "new" LLVM license.

### PR DESCRIPTION
**Pull request by paulhuggett**

### CODE REVIEW

**Review by MaggieYingYi — COMMENTED** [review]
In the rld project, all files include the path, for example:
```
//===- unit_tests/rld/TestXfxResolver.cpp ---------------------------------===//
```
However, in the LLVM project, the file doesn’t include the path. 
```
//===- TestXfxResolver.cpp ---------------------------------===//
```
Does that mean that the rld project will not follow the LLVM project standard?

**Comment by paulhuggett** [comment]
> Does that mean that the rld project will not follow the LLVM project standard?

Perhaps. The example in the code standards documentation [here](https://llvm.org/docs/CodingStandards.html#file-headers) _does_ appear to include the path.

**Comment by MaggieYingYi** [comment]
LGTM! Tom probably need to give the final authority.

**Review by Spiny-Norman — APPROVED** [review]
> btw, some of the ascii-art in the header comment block is missing the "Test" part of the name, eg, "TestMathExtras.cpp" gets ascii-art-ified as "MathExtras". 

Yes, that’s deliberate.

> A minor thing though. (Also do we even need this ascii art?)

Need? No. It’s there because I like it and because I used the same tool that stamps the boilerplate text for the pstore library.

**Pull request merged**
