### PR TITLE
Rgallop/master/add rld

### PR DESCRIPTION
**Pull request by rgal**
Combine rld into main program repo repository.

Moved git submodule file to the top level of the repo and enabled it in github actions workflow.

### CODE REVIEW

**Comment by MaggieYingYi** [comment]
> 
> 
> > Did I miss something?
> 
> It is missing the xxHash directory which it managed as a git submodule (a git repo within a git repo). You'll need to clone the submodules, see here: https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules

Thank. Should the README.md file need to be updated to show how to build llvm-prohect-prepo with rld? For xxHash submodule, do we need add a step (similar as pstore project) in the README.md?

**Comment by rgal** [comment]
> > > Did I miss something?
> > 
> > 
> > It is missing the xxHash directory which it managed as a git submodule (a git repo within a git repo). You'll need to clone the submodules, see here: https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
> 
> Thank.
> 
> 1. Why does `rld` need `xxHAsh` and `lld` doesn't?

I don't know. @paulhuggett added this dependency in rld.

> 2. For `xxHash` submodule, do we need add a step (similar as `pstore` project) in the `README.md`?

We could do, but only if we want to describe how to build rld as well. Do we want to do that yet?

> 3. Should the `README.md` file need to be updated to show how to build `llvm-prohect-prepo` with `rld`?

If we do that now, we would need to be very clear about the status of rld compared to linking with repo2obj. @paulhuggett do you think we should do this yet?

**Comment by paulhuggett** [comment]
> If we do that now, we would need to be very clear about the status of rld compared to linking with repo2obj. @paulhuggett do you think we should do this yet?

No, I think it’s too early. rld isn’t in anything like a state to be use for actually linking anything yet.

**Comment by paulhuggett** [comment]
> Why does rld need xxHAsh and lld doesn't?

rld-gen (not rld itself, at least ATM) uses xxHash to generate hashes for the compilations and fragments that it builds. Please refer to issue #68 for the reasoning. lld doesn’t use it because… it doesn’t!

**Pull request merged**
