### PR TITLE
Rgallop/master/merge llvm 11.x

### PR DESCRIPTION
**Pull request by rgal**
Merge LLVM 11.x branch point, (also see changes to pstore https://github.com/SNSystems/pstore/pull/64).

This builds (X86 target) and passes check-all, builds a stage 2 with empty database (1928 seconds) and after ninja clean (1344 seconds).

This contains a commit to use the corresponding branch from pstore which I will not commit.

I made fixes to get build and test going as follow up commits that can be reviewed.

I have created a task: #117 to review the use of report_fatal_error() since the changes here: https://reviews.llvm.org/D67847

### CODE REVIEW

**Review by paulhuggett — APPROVED** [review]
A “review” isn’t really feasible but if the tests pass, we ought to be good!

**Review by MaggieYingYi — COMMENTED** [review]
Did you build a large project (e.g. upstream llvm-project) using the built repo compiler? Did you build twice with and without the existing repository?

**Comment by rgal** [comment]
> Did you build a large project (e.g. upstream llvm-project) using the built repo compiler? Did you build twice with and without the existing repository?

I built the repo compiler itself twice, first time without clang.db, then with.

**Comment by MaggieYingYi** [comment]
>
> I built the repo compiler itself twice, first time without clang.db, then with.
>

Thanks, Russ.

**Comment by MaggieYingYi** [comment]
LGTM!

**Pull request merged**
